import { useMemo, useState } from "react";
import { Check, Droplets, Save, ShieldCheck, Sparkles, Sun, Thermometer, Users, Wind } from "lucide-react";
import { ACTION_COPY, BAND_LABEL, humanize } from "../productUtils.js";
import { cToF, loadCrewMap, loadSelectedSiteId, loadSites, writeStorage } from "./planWorkspace.js";

const ACTIONS=["Outdoor work","Work","Shade break","Recovery","Hydration","Indoor work","Prep / setup","Wrap up"];
const planKey="heatshield.plannerDraft.v1";
function blocks(crew){if(!crew.length)return[];const toMinutes=(v)=>{const [h,m]=String(v).split(":").map(Number);return h*60+m};const start=Math.min(...crew.map(w=>toMinutes(w.shiftStart||"06:00")));const end=Math.max(...crew.map(w=>toMinutes(w.shiftEnd||"14:00")));return Array.from({length:Math.min(10,Math.ceil((end-start)/60))},(_,i)=>({id:String(start+i*60),start:`${String(Math.floor((start+i*60)/60)).padStart(2,"0")}:00`,end:`${String(Math.floor((start+(i+1)*60)/60)).padStart(2,"0")}:00`}));}
export default function CreatePlanScreen({location,weather,cycle,onNavigate}){
 const data=useMemo(()=>{const sites=loadSites(location),id=loadSelectedSiteId(sites),site=sites.find(s=>s.id===id)||sites[0];return{site,crew:site?(loadCrewMap()[site.id]||[]):[]}},[location]);
 const rows=useMemo(()=>blocks(data.crew),[data.crew]);
 const initial=useMemo(()=>Object.fromEntries(rows.map((r,i)=>[r.id,Object.fromEntries(data.crew.map(w=>[w.workerId,i===0?"Prep / setup":i===rows.length-1?"Wrap up":w.outdoor?"Outdoor work":"Indoor work"]))])),[data.crew,rows]);
 const [baseline]=useState(initial),[planner,setPlanner]=useState(initial),[mode,setMode]=useState("planner"),[notes,setNotes]=useState(""),[compare,setCompare]=useState(false),[finalize,setFinalize]=useState(false),[saved,setSaved]=useState("");
 const plan=mode==="ai"?baseline:planner;const current=weather?.current||{},band=cycle?.current_assessment?.screening?.band,actions=cycle?.agent_decision?.actions||[];
 const diffs=rows.flatMap(r=>data.crew.filter(w=>baseline[r.id]?.[w.workerId]!==planner[r.id]?.[w.workerId]).map(w=>`${w.name||w.workerId} · ${r.start}: ${baseline[r.id][w.workerId]} → ${planner[r.id][w.workerId]}`));
 const persist=(status)=>{writeStorage(planKey,{site_id:data.site?.id,status,updated_at:new Date().toISOString(),schedule:planner,notes});setSaved(status==="finalized"?"Plan finalized":"Draft saved");setFinalize(false)};
 return <div className="hs-screen hs-cp"><div className="hs-cp-toolbar"><strong>Plan <b>›</b> Create Plan</strong><div><button onClick={()=>persist("draft")}><Save/>Save draft</button><button onClick={()=>setCompare(true)}>Compare Plans</button><button className="primary" onClick={()=>setFinalize(true)}>Finalize Plan <Check/></button></div></div>
 <section className="hs-cp-context"><div><strong>{data.site?.name||"No worksite"}</strong><small>{data.site?.timezone}</small><span>{data.site?.address||"Location unavailable"}</span><button onClick={()=>onNavigate("site-setup")}>Change site</button></div><div className="weather"><Sun/><strong>{cToF(current.temperature_2m_c)??"--"}°F</strong><span>{current.condition||"Weather unavailable"}</span></div><dl><div><dt><Thermometer/>Heat Index</dt><dd>{cToF(cycle?.current_assessment?.environmental_evidence?.heat_index_c)??"--"}°F</dd></div><div><dt><Droplets/>Humidity</dt><dd>{current.relative_humidity_percent??"--"}%</dd></div><div><dt><Wind/>Wind</dt><dd>{current.wind_speed_kmh?Math.round(current.wind_speed_kmh*.621371):"--"} mph</dd></div></dl><div><strong>{data.crew.length} Active Workers</strong><small>Worker-specific planning</small></div></section>
 {saved?<div className="hs-cp-saved"><ShieldCheck/>{saved}</div>:null}<div className="hs-cp-steps"><span className="active"><b>1</b>AI Recommendations</span><span><b>2</b>Review & Modify</span><span><b>3</b>Plan Summary</span><div><button className={mode==="ai"?"active":""} onClick={()=>setMode("ai")}><Sparkles/>AI</button><button className={mode==="planner"?"active":""} onClick={()=>setMode("planner")}><Users/>Planner</button></div></div>
 <div className="hs-cp-grid"><aside className="hs-cp-ai"><h2>AI Recommended Plan</h2>{actions.length?actions.map(a=><article key={a.action_id}><strong>{ACTION_COPY[a.action_type]?.title||humanize(a.action_type)}</strong><small>{humanize(a.status)} · supervisor review</small><p>{ACTION_COPY[a.action_type]?.how||"Structured recommendation from current evidence."}</p><button>View evidence</button></article>):<div className="empty"><Sparkles/><strong>AI recommendations unavailable</strong><span>Run the current heat analysis; manual planning remains available.</span></div>}</aside>
 <main className="hs-cp-editor"><header><h2>Review & Modify Plan</h2><span>{mode==="ai"?"Viewing immutable AI baseline":"Edit worker assignments"}</span></header>{data.crew.length?<div className="table"><table><thead><tr><th>Time</th>{data.crew.map(w=><th key={w.workerId}>{w.name||w.workerId}<small>{w.workerId}</small></th>)}<th>Conditions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><th>{r.start}–{r.end}</th>{data.crew.map(w=><td key={w.workerId}><select disabled={mode==="ai"} value={plan[r.id]?.[w.workerId]} onChange={e=>{setMode("planner");setPlanner(p=>({...p,[r.id]:{...p[r.id],[w.workerId]:e.target.value}}))}}>{ACTIONS.map(a=><option key={a}>{a}</option>)}</select><small>{w.zoneLabel||"Work area"}</small></td>)}<td><strong>{cToF(current.temperature_2m_c)??"--"}°F</strong><small>{BAND_LABEL[band]||"Unavailable"}</small></td></tr>)}</tbody></table></div>:<div className="empty"><Users/><strong>No workers added</strong><button onClick={()=>onNavigate("map")}>Add workers on Map</button></div>}</main>
 <aside className="hs-cp-summary"><section><h2>Plan Summary</h2><p><span>Heat Risk for Shift</span><strong>{BAND_LABEL[band]||"Unavailable"}</strong></p></section><section><h3>Plan Impact</h3><p><span>Workers covered</span><strong>{data.crew.length}</strong></p><p><span>Planner modifications</span><strong>{diffs.length}</strong></p></section><section><h3>Key Evidence Used</h3><p><span>Heat map</span><strong>{cycle?.spatial_heat?"FortyGuard":"Unavailable"}</strong></p><p><span>Environmental data</span><strong>{cycle?"Current cycle":"Unavailable"}</strong></p></section><section><h3>Notes</h3><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Operational notes"/></section></aside></div>
 {compare?<div className="hs-cp-modal"><div><h2>AI baseline vs Planner plan</h2>{diffs.length?diffs.map(d=><p key={d}>{d}</p>):<p>No modifications yet.</p>}<button onClick={()=>setCompare(false)}>Back to review</button></div></div>:null}{finalize?<div className="hs-cp-modal"><div><h2>Finalize plan for {data.crew.length} workers?</h2><p>Residual risk: {BAND_LABEL[band]||"Unavailable"}</p><footer><button onClick={()=>setFinalize(false)}>Back to review</button><button className="primary" onClick={()=>persist("finalized")}>Finalize Plan</button></footer></div></div>:null}</div>
}
